baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = false

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    #style = 'github-dark'
    tabWidth = 4

[languages]
  [languages.en]
    title = "Andy Sukowski-Bang"
    subtitle = "Student & Programmer"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "cd ~/"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "pgp"
        name = "PGP"
        url = "/pgp"
  [languages.de]
    title = "Andy Sukowski-Bang"
    subtitle = "Student & Programmierer"
    keywords = ""
    copyright = ""
    menuMore = "Mehr anzeigen"
    writtenBy = "Geschrieben von"
    readMore = "Weiterlesen"
    readOtherPosts = "Andere Beiträge lesen"
    newerPosts = "Neuere Beiträge"
    olderPosts = "Ältere Beiträge"
    minuteReadingTime = "Minuten"
    dateFormatSingle = "02.01.2006"
    dateFormatList = "02.01.2006"

    [languages.de.params.logo]
      logoText = "cd ~/"
      logoHomeLink = "/"

    [languages.de.menu]
      [[languages.de.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts"
      [[languages.de.menu.main]]
        identifier = "pgp"
        name = "PGP"
        url = "/pgp"
